### ISSUE TITLE
datomic.samples.TxFunctions#main does not work for java 11

### ISSUE THREAD

**Issue by nikolayandr** [Datomic/datomic-java-examples#4]
In this case 
```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException
	at datomic.promise$throw_executionexception_if_throwable.invoke(promise.clj:10)
	at datomic.promise$settable_future$reify__6471.deref(promise.clj:54)
	at clojure.core$deref.invoke(core.clj:2206)
	at datomic.promise$settable_future$reify__6471.get(promise.clj:45)
```
is thrown on attempting transact data which contains call to **:examples/ensure-composite**

See more details https://forum.datomic.com/t/transaction-functions-written-in-java-do-not-work-for-datomic-mem-protocol-when-application-is-run-in-java-11/1546

**Comment by toddbrawn-1** [comment]
In this call: 
       results = Peer.query("[:find [?artist-name ...] " +
                           " :in $ ?country [?reference ...] " +
                           " :where [(datomic.api/entid $ ?country) ?country-id] " +
                           "        [?artist :artist/name ?artist-name] " +
                           "        [?artist ?reference ?country-id]]",
                           db, Util.read(":country/BE"), Util.list(Util.read(":artist/country")));

I am getting the following error: java.lang.ClassNotFoundException: datomic.api, compiling:(NO_SOURCE_PATH:0:0)

Can you tell me what configuration I am missing?
